name: "🐞 Reporte de Error (Bug)"
description: "Para informar algo que no funciona como debería."
title: "[BUG]: "
labels: ["bug"]
assignees: ["Lur0y"]
type: bug
body:
  - type: markdown
    attributes:
      value: |
        ### 🚨 Gracias por reportar este error
        Por favor, completa la siguiente información para ayudarnos a resolverlo lo antes posible.

  - type: textarea
    id: descripcion
    attributes:
      label: "❌ Descripción del Problema"
      description: "¿Qué está pasando? Describe el comportamiento erróneo de forma clara."
      placeholder: "Ej: El botón de envío no reacciona al hacer clic..."
    validations:
      required: true

  - type: textarea
    id: pasos
    attributes:
      label: "👣 Pasos para Reproducir"
      description: "Indica la secuencia exacta para ver el error."
      value: |
        1. Ir a '...'
        2. Dar clic en '...'
        3. Ver el error '...'
    validations:
      required: true

  - type: textarea
    id: comportamiento
    attributes:
      label: "📉 Comportamiento Esperado vs. Actual"
      description: "Compara lo que debería pasar con lo que realmente sucede."
      placeholder: "- Esperado: ... \n- Actual: ..."
    validations:
      required: true
